# Simple workflow for generating XML documentation
name: Generate XML Documentation

on:
  # Runs on pushes targeting the default branch and impacting the src_stripped folder
  push:
    branches: ["main"]
    paths: ["src_stripped"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build the XML documentation from the src_stripped files
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check Assembly-CSharp.xml
        run: dir DLL_stripped
        shell: cmd
      - name: Generate XML Documentation Directly
        run: GenDoc\GenDoc.exe src_stripped\Assembly-CSharp-Stripped.sln DLL_stripped
        shell: cmd
      - name: Check Assembly-CSharp.xml
        run: dir DLL_stripped
        shell: cmd
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Assembly-CSharp.xml
          path: DLL_stripped/Assembly-CSharp.xml
