# Simple workflow for generating XML documentation
name: Generate XML Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: ["src_stripped"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#   group: "pages"
#   cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate XML Documentation Directly
        run: |
          GenDoc\GenDoc.exe src_stripped\Assembly-CSharp-Stripped.sln DLL_stripped
          dir DLL_stripped
        shell: cmd
      - name: Upload Artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Assembly-CSharp.xml
          path: DLL_stripped/Assembly-CSharp.xml
      # - name: Generate XML Documentation via Batch File
      #   run: GenDoc.bat
      #   shell: cmd
      # - name: Import-Module
      #   run: Import-Module GenDoc
