# Simple workflow for generating XML documentation
name: Generate XML Documentation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build the XML documentation from the src_stripped files
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check Assembly-CSharp.xml
        run: move DLL_stripped\Assembly-CSharp.xml DLL_stripped\Assembly-CSharp.xml.bak
        shell: cmd
      - name: Generate XML Documentation Directly without Rename
        run: GenDoc\GenDoc.exe src_stripped\Assembly-CSharp-Stripped.sln DLL_stripped
        shell: cmd
      - name: Check Assembly-CSharp.xml
        run: fc DLL_stripped\Assembly-CSharp.xml DLL_stripped\Assembly-CSharp.xml.bak
        shell: cmd
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Assembly-CSharp.xml
          path: DLL_stripped/Assembly-CSharp.xml
